/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.employee.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;FOO_Employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.employee.model.impl.EmployeeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.employee.model.impl.EmployeeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Employee
 * @generated
 */
@ProviderType
public interface EmployeeModel extends BaseModel<Employee>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
	 */

	/**
	 * Returns the primary key of this employee.
	 *
	 * @return the primary key of this employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee.
	 *
	 * @param primaryKey the primary key of this employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the empid of this employee.
	 *
	 * @return the empid of this employee
	 */
	public long getEmpid();

	/**
	 * Sets the empid of this employee.
	 *
	 * @param empid the empid of this employee
	 */
	public void setEmpid(long empid);

	/**
	 * Returns the ename of this employee.
	 *
	 * @return the ename of this employee
	 */
	@AutoEscape
	public String getEname();

	/**
	 * Sets the ename of this employee.
	 *
	 * @param ename the ename of this employee
	 */
	public void setEname(String ename);

	/**
	 * Returns the dept ID of this employee.
	 *
	 * @return the dept ID of this employee
	 */
	public long getDeptId();

	/**
	 * Sets the dept ID of this employee.
	 *
	 * @param deptId the dept ID of this employee
	 */
	public void setDeptId(long deptId);

	/**
	 * Returns the email address of this employee.
	 *
	 * @return the email address of this employee
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this employee.
	 *
	 * @param emailAddress the email address of this employee
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the hr name of this employee.
	 *
	 * @return the hr name of this employee
	 */
	@AutoEscape
	public String getHrName();

	/**
	 * Sets the hr name of this employee.
	 *
	 * @param hrName the hr name of this employee
	 */
	public void setHrName(String hrName);

	/**
	 * Returns the assigned teams ID of this employee.
	 *
	 * @return the assigned teams ID of this employee
	 */
	public long getAssignedTeamsId();

	/**
	 * Sets the assigned teams ID of this employee.
	 *
	 * @param assignedTeamsId the assigned teams ID of this employee
	 */
	public void setAssignedTeamsId(long assignedTeamsId);

	/**
	 * Returns the user ID of this employee.
	 *
	 * @return the user ID of this employee
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this employee.
	 *
	 * @param userId the user ID of this employee
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee.
	 *
	 * @return the user uuid of this employee
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this employee.
	 *
	 * @param userUuid the user uuid of this employee
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this employee.
	 *
	 * @return the group ID of this employee
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employee.
	 *
	 * @param groupId the group ID of this employee
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee.
	 *
	 * @return the company ID of this employee
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee.
	 *
	 * @param companyId the company ID of this employee
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this employee.
	 *
	 * @return the create date of this employee
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee.
	 *
	 * @param createDate the create date of this employee
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee.
	 *
	 * @return the modified date of this employee
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee.
	 *
	 * @param modifiedDate the modified date of this employee
	 */
	public void setModifiedDate(Date modifiedDate);

}