/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.training.customsql.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Training service. Represents a row in the &quot;CSQL_Training&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.training.customsql.model.impl.TrainingModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.training.customsql.model.impl.TrainingImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Training
 * @generated
 */
@ProviderType
public interface TrainingModel extends BaseModel<Training>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a training model instance should use the {@link Training} interface instead.
	 */

	/**
	 * Returns the primary key of this training.
	 *
	 * @return the primary key of this training
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this training.
	 *
	 * @param primaryKey the primary key of this training
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this training.
	 *
	 * @return the uuid of this training
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this training.
	 *
	 * @param uuid the uuid of this training
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the training ID of this training.
	 *
	 * @return the training ID of this training
	 */
	public long getTrainingId();

	/**
	 * Sets the training ID of this training.
	 *
	 * @param trainingId the training ID of this training
	 */
	public void setTrainingId(long trainingId);

	/**
	 * Returns the user ID of this training.
	 *
	 * @return the user ID of this training
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this training.
	 *
	 * @param userId the user ID of this training
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this training.
	 *
	 * @return the user uuid of this training
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this training.
	 *
	 * @param userUuid the user uuid of this training
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the company ID of this training.
	 *
	 * @return the company ID of this training
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this training.
	 *
	 * @param companyId the company ID of this training
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this training.
	 *
	 * @return the group ID of this training
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this training.
	 *
	 * @param groupId the group ID of this training
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the training name of this training.
	 *
	 * @return the training name of this training
	 */
	@AutoEscape
	public String getTrainingName();

	/**
	 * Sets the training name of this training.
	 *
	 * @param trainingName the training name of this training
	 */
	public void setTrainingName(String trainingName);

}