/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LibraryStore service. Represents a row in the &quot;LMS_LibraryStore&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.lms.model.impl.LibraryStoreModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.lms.model.impl.LibraryStoreImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LibraryStore
 * @generated
 */
@ProviderType
public interface LibraryStoreModel
	extends BaseModel<LibraryStore>, GroupedModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a library store model instance should use the {@link LibraryStore} interface instead.
	 */

	/**
	 * Returns the primary key of this library store.
	 *
	 * @return the primary key of this library store
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this library store.
	 *
	 * @param primaryKey the primary key of this library store
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this library store.
	 *
	 * @return the uuid of this library store
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this library store.
	 *
	 * @param uuid the uuid of this library store
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the lms ID of this library store.
	 *
	 * @return the lms ID of this library store
	 */
	public long getLmsID();

	/**
	 * Sets the lms ID of this library store.
	 *
	 * @param lmsID the lms ID of this library store
	 */
	public void setLmsID(long lmsID);

	/**
	 * Returns the bookname of this library store.
	 *
	 * @return the bookname of this library store
	 */
	@AutoEscape
	public String getBookname();

	/**
	 * Sets the bookname of this library store.
	 *
	 * @param bookname the bookname of this library store
	 */
	public void setBookname(String bookname);

	/**
	 * Returns the issue date of this library store.
	 *
	 * @return the issue date of this library store
	 */
	@AutoEscape
	public String getIssueDate();

	/**
	 * Sets the issue date of this library store.
	 *
	 * @param issueDate the issue date of this library store
	 */
	public void setIssueDate(String issueDate);

	/**
	 * Returns the uploaded by of this library store.
	 *
	 * @return the uploaded by of this library store
	 */
	@AutoEscape
	public String getUploadedBy();

	/**
	 * Sets the uploaded by of this library store.
	 *
	 * @param uploadedBy the uploaded by of this library store
	 */
	public void setUploadedBy(String uploadedBy);

	/**
	 * Returns the issue to of this library store.
	 *
	 * @return the issue to of this library store
	 */
	@AutoEscape
	public String getIssueTo();

	/**
	 * Sets the issue to of this library store.
	 *
	 * @param issueTo the issue to of this library store
	 */
	public void setIssueTo(String issueTo);

	/**
	 * Returns the author name of this library store.
	 *
	 * @return the author name of this library store
	 */
	@AutoEscape
	public String getAuthorName();

	/**
	 * Sets the author name of this library store.
	 *
	 * @param authorName the author name of this library store
	 */
	public void setAuthorName(String authorName);

	/**
	 * Returns the group ID of this library store.
	 *
	 * @return the group ID of this library store
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this library store.
	 *
	 * @param groupId the group ID of this library store
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this library store.
	 *
	 * @return the company ID of this library store
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this library store.
	 *
	 * @param companyId the company ID of this library store
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this library store.
	 *
	 * @return the user ID of this library store
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this library store.
	 *
	 * @param userId the user ID of this library store
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this library store.
	 *
	 * @return the user uuid of this library store
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this library store.
	 *
	 * @param userUuid the user uuid of this library store
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this library store.
	 *
	 * @return the user name of this library store
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this library store.
	 *
	 * @param userName the user name of this library store
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this library store.
	 *
	 * @return the create date of this library store
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this library store.
	 *
	 * @param createDate the create date of this library store
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created date of this library store.
	 *
	 * @return the created date of this library store
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this library store.
	 *
	 * @param createdDate the created date of this library store
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this library store.
	 *
	 * @return the modified date of this library store
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this library store.
	 *
	 * @param modifiedDate the modified date of this library store
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this library store.
	 *
	 * @return the status of this library store
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this library store.
	 *
	 * @param status the status of this library store
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this library store.
	 *
	 * @return the status by user ID of this library store
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this library store.
	 *
	 * @param statusByUserId the status by user ID of this library store
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this library store.
	 *
	 * @return the status by user uuid of this library store
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this library store.
	 *
	 * @param statusByUserUuid the status by user uuid of this library store
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this library store.
	 *
	 * @return the status by user name of this library store
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this library store.
	 *
	 * @param statusByUserName the status by user name of this library store
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this library store.
	 *
	 * @return the status date of this library store
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this library store.
	 *
	 * @param statusDate the status date of this library store
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this library store is approved.
	 *
	 * @return <code>true</code> if this library store is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this library store is denied.
	 *
	 * @return <code>true</code> if this library store is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this library store is a draft.
	 *
	 * @return <code>true</code> if this library store is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this library store is expired.
	 *
	 * @return <code>true</code> if this library store is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this library store is inactive.
	 *
	 * @return <code>true</code> if this library store is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this library store is incomplete.
	 *
	 * @return <code>true</code> if this library store is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this library store is pending.
	 *
	 * @return <code>true</code> if this library store is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this library store is scheduled.
	 *
	 * @return <code>true</code> if this library store is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}