/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LibraryStore service. Represents a row in the &quot;LMS_LibraryStore&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.lms.model.impl.LibraryStoreModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.lms.model.impl.LibraryStoreImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LibraryStore
 * @generated
 */
@ProviderType
public interface LibraryStoreModel extends BaseModel<LibraryStore> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a library store model instance should use the {@link LibraryStore} interface instead.
	 */

	/**
	 * Returns the primary key of this library store.
	 *
	 * @return the primary key of this library store
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this library store.
	 *
	 * @param primaryKey the primary key of this library store
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lms ID of this library store.
	 *
	 * @return the lms ID of this library store
	 */
	public long getLmsID();

	/**
	 * Sets the lms ID of this library store.
	 *
	 * @param lmsID the lms ID of this library store
	 */
	public void setLmsID(long lmsID);

	/**
	 * Returns the bookname of this library store.
	 *
	 * @return the bookname of this library store
	 */
	@AutoEscape
	public String getBookname();

	/**
	 * Sets the bookname of this library store.
	 *
	 * @param bookname the bookname of this library store
	 */
	public void setBookname(String bookname);

	/**
	 * Returns the issue date of this library store.
	 *
	 * @return the issue date of this library store
	 */
	@AutoEscape
	public String getIssueDate();

	/**
	 * Sets the issue date of this library store.
	 *
	 * @param issueDate the issue date of this library store
	 */
	public void setIssueDate(String issueDate);

	/**
	 * Returns the uploaded by of this library store.
	 *
	 * @return the uploaded by of this library store
	 */
	@AutoEscape
	public String getUploadedBy();

	/**
	 * Sets the uploaded by of this library store.
	 *
	 * @param uploadedBy the uploaded by of this library store
	 */
	public void setUploadedBy(String uploadedBy);

	/**
	 * Returns the issue to of this library store.
	 *
	 * @return the issue to of this library store
	 */
	@AutoEscape
	public String getIssueTo();

	/**
	 * Sets the issue to of this library store.
	 *
	 * @param issueTo the issue to of this library store
	 */
	public void setIssueTo(String issueTo);

	/**
	 * Returns the group ID of this library store.
	 *
	 * @return the group ID of this library store
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this library store.
	 *
	 * @param groupId the group ID of this library store
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the comapny ID of this library store.
	 *
	 * @return the comapny ID of this library store
	 */
	public long getComapnyId();

	/**
	 * Sets the comapny ID of this library store.
	 *
	 * @param comapnyId the comapny ID of this library store
	 */
	public void setComapnyId(long comapnyId);

	/**
	 * Returns the user ID of this library store.
	 *
	 * @return the user ID of this library store
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this library store.
	 *
	 * @param userId the user ID of this library store
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this library store.
	 *
	 * @return the user uuid of this library store
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this library store.
	 *
	 * @param userUuid the user uuid of this library store
	 */
	public void setUserUuid(String userUuid);

}